# Generated by Django 5.0.1 on 2024-02-11 00:23

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='profile_image',
            field=models.ImageField(blank=True, default=app.models.get_default_profile_image, max_length=255, null=True, upload_to=app.models.get_profile_image_filepath),
        ),
    ]
